name: ci

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  test_django:
    uses: seunghayim/django2/.github/workflows/django_test.yml@main
  build:
    runs-on: ubuntu-latest
    needs: [test_django]
    steps:
      - name: Set the ip value
        run: |
          echo "ip_address=$(curl ifconfig.io)" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build dockerfile
        run: |
          DOCKER_BUILDKIT=1 docker build \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:latest \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${GITHUB_SHA::7}-${GITHUB_RUN_NUMBER} .
    
      - name: Push docker images
        run: |
          DOCKER_BUILDKIT=1 docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }} --all-tags

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.EKS_REGION }}

      - name: Connect to EKS cluster 
        run: aws eks --region ${{ secrets.EKS_REGION }} update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}
    
      - name: Update deployment secrets
        run: |
          cat << EOF >> .env-secret
          DJANGO_SUPERUSER_USERNAME=${{ secrets.DJANGO_SUPERUSER_USERNAME }}
          DJANGO_SUPERUSER_PASSWORD=${{ secrets.DJANGO_SUPERUSER_PASSWORD }}
          DJANGO_SUERPUSER_EMAIL=${{ secrets.DJANGO_SUERPUSER_EMAIL }}
          DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
          ENV_ALLOWED_HOST=${{ secrets.ENV_ALLOWED_HOST }}
          MARIADB_DATABASE=${{ secrets.MARIADB_DATABASE }}
          MARIADB_PASSWORD=${{ secrets.MARIADB_PASSWORD }}
          MARIADB_USER=${{ secrets.MARIADB_USER }}
          MARIADB_HOST=${{ secrets.MARIADB_HOST }}
          MARIADB_PORT=${{ secrets.MARIADB_PORT }}
          EOF
          kubectl delete secret django-secret
          kubectl create secret generic django-secret --from-env-file=.env-secret

      - name: deploy
        run: |
          kubectl set image deploy/was-deploy django=${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${GITHUB_SHA::7}-${GITHUB_RUN_NUMBER}

      - name: rollout status
        run: |
          kubectl rollout status deploy/was-deploy

      - name: Run migrate.sh / collectstatic.sh
        run: |
          export POD_NAME=$(kubectl get pod -l app=was -o jsonpath="{.items[0].metadata.name}")
          kubectl exec -it $POD_NAME -- bash /app/migrate.sh
          kubectl exec -it $POD_NAME -- bash /app/collectstatic.sh
